### ISSUE TITLE
When an item is added to a collection, the collection is reindexed by the wrong to_solr

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/hydra-collections#11]
It's calling ActiveFedora::Base.to_solr rather than the to_solr method on the specific subclass.

I believe this was introduced by this change:

https://github.com/projecthydra/hydra-collections/commit/d0958312d00036faa8584a5d05b593778ca3a691

**Comment by jcoyne** [comment]
@cam156 Can I close this?  Is this still a problem?

**Comment by cam156** [comment]
@jcoyne I was never able to replicate the issue.  I'm guessing with all the changes it is now a non issue.
