### ISSUE TITLE
Cut new gem version

### ISSUE THREAD

**Issue by grosscol** [projecthydra/hydra-collections#92]

**Comment by flyingzumwalt** [comment]
+1

**Comment by flyingzumwalt** [comment]
curation_concerns-models master currently lists hydra-collections (~> 6.0.0.rc1) in its gemspec but the rc1 was never released.

**Comment by flyingzumwalt** [comment]
scratch that last comment.  I had an old copy of spec/internal.

**Comment by jcoyne** [comment]
6.0.0 was released on 4 Jan 2016
